from fpdf import FPDF

class ProfessionalPDF(FPDF):
    def header(self):
        # 1. Top Color Bar (Visual Flair)
        self.set_fill_color(52, 73, 94) # Dark Blue/Grey
        self.rect(0, 0, 210, 25, 'F')
        
        # 2. Title inside the bar
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(255, 255, 255) # White
        self.set_xy(10, 8)
        self.cell(0, 10, 'MONTHLY SYSTEM REPORT', 0, 0, 'L')
        
        # 3. Logo/Company Name on right
        self.set_font('Helvetica', 'I', 10)
        self.set_xy(0, 8)
        self.cell(200, 10, 'Generated by ACME Corp System', 0, 0, 'R')
        self.ln(25) # Add spacing after header

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128) # Grey
        self.cell(0, 10, f'Page {self.page_no()} | Confidential Document', 0, 0, 'C')

    def add_info_section(self):
        """Adds a summary section before the table"""
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, 'Client Details', 0, 1)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        
        # Simple text block
        self.cell(0, 5, 'Client:   Global Tech Industries', 0, 1)
        self.cell(0, 5, 'Date:     December 07, 2025', 0, 1)
        self.cell(0, 5, 'Ref ID:   #9928-AB', 0, 1)
        self.ln(10) # Gap before table

    def add_data_table(self, header, data):
        # --- Table Configuration ---
        col_widths = [90, 40, 60] # Width of columns (Total = 190)
        line_height = 10
        
        # --- Header Row ---
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(230, 230, 230) # Light Grey
        self.set_text_color(0, 0, 0)
        self.set_draw_color(200, 200, 200) # Grey lines
        
        for i, h in enumerate(header):
            align = 'R' if i == 2 else 'L' # Align price to Right
            self.cell(col_widths[i], line_height, h, border=1, align=align, fill=True)
        self.ln()

        # --- Data Rows ---
        self.set_font('Helvetica', '', 10)
        fill = False # For striping
        
        total_sum = 0
        
        for row in data:
            # Striped row logic
            if fill:
                self.set_fill_color(248, 248, 248) # Very light grey
            else:
                self.set_fill_color(255, 255, 255) # White
            
            # Draw cells
            self.cell(col_widths[0], line_height, row[0], border='LR', align='L', fill=fill)
            self.cell(col_widths[1], line_height, str(row[1]), border='LR', align='C', fill=fill)
            self.cell(col_widths[2], line_height, f"${row[2]:,.2f}", border='LR', align='R', fill=fill)
            
            total_sum += row[2]
            self.ln()
            fill = not fill
            
        # --- Bottom Border ---
        self.cell(sum(col_widths), 0, '', 'T') # Draw a line at the bottom of the table
        self.ln()
        
        # --- Total Row ---
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(230, 240, 255) # Light Blue
        self.cell(col_widths[0] + col_widths[1], line_height, 'TOTAL', border=1, align='R', fill=True)
        self.cell(col_widths[2], line_height, f"${total_sum:,.2f}", border=1, align='R', fill=True)


# --- EXECUTION ---

# 1. Prepare Data
# Format: (Description, Quantity, Price)
table_data = [
    ("Server Maintenance (AWS)", 10, 150.00),
    ("Database Optimization", 5, 300.50),
    ("API License Renewal", 1, 1200.00),
    ("Security Audit (Q4)", 1, 950.00),
]

# 2. Generate PDF
pdf = ProfessionalPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

pdf.add_info_section()
pdf.add_data_table(["Description", "Hours/Qty", "Price"], table_data)

# 3. Output
pdf.output("improved_system_report.pdf")
print("PDF Generated Successfully: improved_system_report.pdf")